### ISSUE TITLE
rumor_card 一行不够啦

### ISSUE THREAD

**Issue by xster** [fluttercandies/ncov_2019#7]
https://github.com/fluttercandies/ncov_2019/blob/f23ae18b7d4def025647ba8a70840890c0e3bf8c/lib/widget/card/rumor_card.dart#L36

![Screenshot_20200216_001822_com example ncov_2019](https://user-images.githubusercontent.com/156888/74601357-3716c180-5052-11ea-835e-510fef8c86f3.jpg)

这样子好多东西看不见的啦

**Comment by ahyangnb** [comment]
感谢反馈，马上更改
